### ISSUE TITLE
Help visibility toggling issue

### ISSUE THREAD

**Issue by rafspiny** [jf-simon/enotes#2]
When in a note, pressing **F1** will toggle the `enotes help`
The help says that F1 will "show/hide this help" but it does hide the help.

Maybe it is by design, but the entry description for the **F1** key is misleading.
I have to click on a note and then press **F1** to make it disappear.

**Comment by jf-simon** [comment]
there is a bug in efl. 
i reported it, 
we need to wait

**Comment by jf-simon** [comment]
with 
0a678e5
key events are working.
i had to set the entry editable to get it working.
if this bug is fixed in efl. i will disable it again.
